---
- name: Add pam_tally2 auth rule
  become: yes
  pamd:
    name: "{{ item }}"
    type: auth
    control: sufficient
    module_path: "{{ module_path }}"
    new_type: auth
    new_control: required
    new_module_path: "{{ tally_module }}"
    module_arguments: "{{ tally_options }}"
    state: before
  with_items:
    "{{ pam_files }}"
    
- name: Add pam_tally2 account rule
  become: yes
  pamd:
    name: "{{ item }}"
    type: account
    control: required
    module_path: "{{ module_path }}"
    new_type: account
    new_control: required
    new_module_path: "{{ tally_module }}"
    state: before
  with_items:
    "{{ pam_files }}"

- name: Set pam_unix password options
  become: yes
  pamd:
    name: "{{ item[0] }}"
    type: password
    control: sufficient
    module_path: "{{ module_path }}"
    module_arguments: "{{ item[1] }}"
    state: args_present
    #   state: updated
  with_nested:
    - "{{ pam_files }}"
    - "{{ unix_options }}"
    
- name: Remove nullok from pam_unix password
  become: yes
  pamd:
    name: "{{ item[0] }}"
    type: "{{ item[1] }}"
    control: sufficient
    module_path: "{{ module_path }}"
    module_arguments: 'nullok'
    state: args_absent
  with_nested:
    - "{{ pam_files }}"
    - [ 'auth', 'account', 'password', 'session' ]
    
- name: Set password complexity
  become: yes
  pamd:
    name: "{{ item[0] }}"
    type: password
    control: requisite
    module_path: "{{ item[2] }}"
    module_arguments: "{{ item[1] }}"
    state: args_present
    #    state: updated
  with_nested:
    - "{{ pam_files }}"
    - "{{ password_options }}"
    - "{{ password_modules }}"


    
    